[package]
name = "rd-plugin-transfer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
rd-core = { path = "../rd-core" }
rd-db = { path = "../rd-db" }
rd-files = { path = "../rd-files" }
rd-http = { path = "../rd-http" }
rd-plugin-host = { path = "../rd-plugin-host" }
rd-scheduler = { path = "../rd-scheduler" }
rustls.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true

[lints]
workspace = true

[dev-dependencies]
rd-core = { path = "../rd-core" }
rd-db = { path = "../rd-db" }
rd-limits = { path = "../rd-limits" }
tempfile.workspace = true
toml.workspace = true
