[package]
name = "rd-plugin-premiumize-crawler"
version = "1.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
plugin-common = { path = "../common" }
plugin-guest-crawler = { path = "../guest-crawler" }
premiumize-common = { path = "../premiumize-common" }

[lib]
crate-type = ["rlib", "cdylib"]

[package.metadata.component]
package = "rdownloader:premiumize-crawler"

[package.metadata.component.target]
path = "../../crates/rd-plugin-api/wit"
world = "crawler-plugin"

[lints]
workspace = true
