[package]
name = "rd-plugin-telegram-notifier"
version = "1.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
wit-bindgen.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[package.metadata.component]
package = "rdownloader:telegram-notifier"

[package.metadata.component.target]
path = "../../crates/rd-plugin-api/wit"
world = "notifier-plugin"

[lints]
workspace = true
