//! Download queue, packages and post-processing routes.

use axum::{
    Router,
    routing::{delete, get, post},
};
use utoipa::OpenApi;

use crate::{
    AppState, download_handlers, download_sources, package_clear, package_export, package_handlers,
    postprocess_handlers, queue_pause_handlers, queue_search, stop_mark_handlers,
};

/// Session-authenticated routes of this area.
pub(crate) fn routes() -> Router<AppState> {
    Router::new()
        .route(
            "/api/v1/downloads",
            get(download_handlers::list_downloads).post(download_handlers::create_download),
        )
        .route(
            "/api/v1/downloads/summary",
            get(download_handlers::download_summary),
        )
        .route(
            "/api/v1/downloads/rates",
            get(download_handlers::download_rates),
        )
        .route(
            "/api/v1/downloads/bulk",
            post(download_handlers::bulk_downloads),
        )
        .route(
            "/api/v1/queue/pause",
            get(queue_pause_handlers::get_queue_pause)
                .put(queue_pause_handlers::pause_queue)
                .delete(queue_pause_handlers::resume_queue),
        )
        .route("/api/v1/queue/search", get(queue_search::search_queue))
        .route(
            "/api/v1/queue/stop-mark",
            get(stop_mark_handlers::get_queue_stop_mark)
                .put(stop_mark_handlers::set_queue_stop_mark)
                .delete(stop_mark_handlers::clear_queue_stop_mark),
        )
        .route(
            "/api/v1/downloads/extract",
            post(download_handlers::extract_downloads),
        )
        .route(
            "/api/v1/downloads/reorder",
            post(package_handlers::reorder_downloads),
        )
        .route(
            "/api/v1/downloads/{id}",
            delete(download_handlers::delete_download).patch(download_handlers::rename_download),
        )
        .route(
            "/api/v1/downloads/{id}/pause",
            post(download_handlers::pause_download),
        )
        .route(
            "/api/v1/downloads/{id}/resume",
            post(download_handlers::resume_download),
        )
        .route(
            "/api/v1/downloads/{id}/cancel",
            post(download_handlers::cancel_download),
        )
        .route(
            "/api/v1/downloads/{id}/reset",
            post(download_handlers::reset_download),
        )
        .route(
            "/api/v1/packages/bulk",
            post(package_handlers::bulk_update_packages),
        )
        .route(
            "/api/v1/packages/reorder",
            post(package_handlers::reorder_packages),
        )
        .route(
            "/api/v1/packages/extract",
            post(package_handlers::extract_packages),
        )
        .route(
            "/api/v1/packages/{id}/extract",
            post(package_handlers::extract_package),
        )
        .route(
            "/api/v1/packages/{id}/extract/force",
            post(package_handlers::force_extract_package),
        )
        .route(
            "/api/v1/packages/{id}/folder",
            post(package_handlers::rename_package_folder),
        )
        .route(
            "/api/v1/packages/{id}/start-after",
            axum::routing::put(package_handlers::set_package_start_after),
        )
        .route(
            "/api/v1/packages/{id}/download-window",
            get(package_handlers::get_package_download_window)
                .put(package_handlers::set_package_download_window),
        )
        .route(
            "/api/v1/packages/{id}/postprocess",
            get(package_handlers::list_package_postprocess),
        )
        .route(
            "/api/v1/packages/{id}",
            axum::routing::patch(package_handlers::update_package)
                .delete(package_handlers::delete_package),
        )
        .route(
            "/api/v1/packages/delete",
            post(package_handlers::delete_packages),
        )
        .route(
            "/api/v1/packages/clear",
            post(package_clear::clear_packages),
        )
        .route(
            "/api/v1/postprocess/queue",
            get(postprocess_handlers::list_postprocess_queue),
        )
        .route(
            "/api/v1/postprocess/scripts",
            get(postprocess_handlers::list_postprocess_scripts),
        )
        .route(
            "/api/v1/postprocess/plugin-steps",
            get(postprocess_handlers::list_plugin_steps),
        )
        .route(
            "/api/v1/postprocess/upload-destinations",
            get(postprocess_handlers::list_upload_destinations),
        )
        .route(
            "/api/v1/postprocess/malware-scanner/test",
            post(postprocess_handlers::test_malware_scanner),
        )
        .route(
            "/api/v1/categories/{id}/postprocess",
            axum::routing::patch(postprocess_handlers::update_category_postprocess),
        )
        .route(
            "/api/v1/postprocess/sort-preview",
            post(postprocess_handlers::preview_category_sorting),
        )
        .route(
            "/api/v1/postprocess/package-name-preview",
            post(postprocess_handlers::preview_package_name),
        )
        .route(
            "/api/v1/downloads/{id}/auth-profile",
            axum::routing::put(download_handlers::set_download_auth_profile),
        )
        .route(
            "/api/v1/downloads/{id}/sources",
            get(download_sources::list_download_sources),
        )
        .route(
            "/api/v1/packages/export",
            post(package_export::export_packages),
        )
        .route(
            "/api/v1/downloads/reresolve",
            post(download_handlers::reresolve_downloads),
        )
}

/// OpenAPI operations of this area.
#[derive(OpenApi)]
#[openapi(paths(
    download_handlers::list_downloads,
    download_handlers::download_summary,
    download_handlers::download_rates,
    download_handlers::create_download,
    download_handlers::pause_download,
    download_handlers::resume_download,
    download_handlers::cancel_download,
    download_handlers::reset_download,
    download_handlers::delete_download,
    download_handlers::rename_download,
    download_handlers::bulk_downloads,
    queue_pause_handlers::get_queue_pause,
    queue_pause_handlers::pause_queue,
    queue_pause_handlers::resume_queue,
    queue_search::search_queue,
    stop_mark_handlers::get_queue_stop_mark,
    stop_mark_handlers::set_queue_stop_mark,
    stop_mark_handlers::clear_queue_stop_mark,
    download_handlers::extract_downloads,
    package_handlers::update_package,
    package_handlers::bulk_update_packages,
    package_handlers::reorder_packages,
    package_handlers::reorder_downloads,
    package_handlers::extract_package,
    package_handlers::force_extract_package,
    package_handlers::rename_package_folder,
    package_handlers::set_package_start_after,
    package_handlers::get_package_download_window,
    package_handlers::set_package_download_window,
    package_handlers::extract_packages,
    package_handlers::delete_package,
    package_handlers::delete_packages,
    package_clear::clear_packages,
    package_handlers::list_package_postprocess,
    postprocess_handlers::list_postprocess_queue,
    postprocess_handlers::list_postprocess_scripts,
    postprocess_handlers::list_plugin_steps,
    postprocess_handlers::list_upload_destinations,
    postprocess_handlers::test_malware_scanner,
    postprocess_handlers::update_category_postprocess,
    postprocess_handlers::preview_category_sorting,
    postprocess_handlers::preview_package_name,
    download_handlers::set_download_auth_profile,
    download_sources::list_download_sources,
    package_export::export_packages,
    download_handlers::reresolve_downloads,
))]
pub(crate) struct Doc;
