[package]
name = "rd-plugin-ddownload"
version = "1.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
url.workspace = true
plugin-common = { path = "../common" }
plugin-guest = { path = "../guest" }
xfs-common = { path = "../xfs-common" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-trait.workspace = true
rd-core = { path = "../../crates/rd-core" }
rd-plugin-api = { path = "../../crates/rd-plugin-api" }

[lib]
crate-type = ["rlib"]

[dev-dependencies]
plugin-common = { path = "../common", features = ["test-support"] }
rd-plugin-api = { path = "../../crates/rd-plugin-api", features = ["test-support"] }
tokio.workspace = true
xfs-common = { path = "../xfs-common", features = ["test-support"] }

[lints]
workspace = true
