[package]
name = "rd-plugin-premiumize-auth"
version = "1.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
plugin-common = { path = "../common" }
plugin-guest-auth = { path = "../guest-auth" }

[lib]
crate-type = ["rlib", "cdylib"]

[lints]
workspace = true
