[package]
name = "rd-subscription"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
croner.workspace = true
quick-xml.workspace = true
regex.workspace = true
rd-collector = { path = "../rd-collector" }
rd-core = { path = "../rd-core" }
rd-media = { path = "../rd-media" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tracing.workspace = true
url.workspace = true
utoipa.workspace = true

[lints]
workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
