//! First-run setup, sign-in, passwords and the pairing and scoping of API tokens.

use super::*;

/// Whether initial setup has been completed.
#[derive(Serialize, ToSchema)]
pub struct AuthStatus {
    pub setup_required: bool,
    pub authenticated: bool,
    /// The administrator login is switched off in the settings; every request is trusted.
    #[serde(default)]
    pub login_disabled: bool,
    /// Whether a passkey is enrolled, so the sign-in screen knows to offer it.
    #[serde(default)]
    pub passkeys_available: bool,
    /// Whether signing in through the identity provider is possible: configured, an identity
    /// bound, and an external URL to come back to (RD-190-15).
    #[serde(default)]
    pub oidc_available: bool,
    /// What the sign-in button calls the provider, when it is offered.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oidc_display_name: Option<String>,
    /// Whether the password form is offered. Off only after a proven provider sign-in, and back
    /// on only from the machine the service runs on (D3).
    pub password_login: bool,
}

/// First-run wizard progress plus what the install already has configured.
#[derive(Serialize, ToSchema)]
pub struct SetupStatus {
    /// Explicit completion flag, or a storage root already exists.
    pub wizard_completed: bool,
    pub storage_roots: u32,
    /// Of those, how many sit on a path that a container restart wipes.
    pub ephemeral_storage_roots: u32,
    pub categories: u32,
    pub capture_agents: u32,
    pub accounts: u32,
    pub usenet_servers: u32,
    /// The service's own download directory, offered as the first storage root.
    ///
    /// The form used to start on a hardcoded `/downloads`, which is right inside the container
    /// image and wrong on every native install — on Linux the filesystem root belongs to another
    /// user, so accepting the suggestion produced a failure. Suggesting the directory the service
    /// actually writes to means the offered value is one it has already created.
    pub suggested_storage_path: String,
}

/// Initial administrator password.
#[derive(Deserialize, ToSchema)]
pub struct SetupRequest {
    #[schema(write_only)]
    pub password: String,
}

/// Administrator login request.
#[derive(Deserialize, ToSchema)]
pub struct LoginRequest {
    #[schema(write_only)]
    pub password: String,
    /// A code from an authenticator app, or a recovery code.
    ///
    /// Optional so the first request can omit it: the client learns that a second factor is
    /// required from the `auth.mfa_required` refusal, rather than having to ask in advance
    /// whether this installation uses one. Asking in advance would tell an unauthenticated
    /// caller something about the account.
    #[serde(default)]
    pub code: Option<String>,
}

/// A change of the administrator password by somebody who knows the current one (RD-120-22).
///
/// Both fields are `write_only`: neither may ever appear in a response, and the generated
/// schema is what keeps a future handler from echoing one back.
#[derive(Deserialize, ToSchema)]
pub struct PasswordChangeRequest {
    /// The password in force now. Wrong is refused exactly as a wrong sign-in is.
    #[schema(write_only)]
    pub current_password: String,
    /// The replacement, judged by the same policy the first password was.
    #[schema(write_only)]
    pub new_password: String,
}

/// A new administrator password set on the machine the service runs on, without the current
/// one (RD-190-24): what `rdownloader auth reset-password` sends with the local control token.
#[derive(Deserialize, ToSchema)]
pub struct PasswordResetRequest {
    /// The new password, judged by the same policy as every other one. Generated by the
    /// command unless the owner typed it (`--prompt`).
    #[schema(write_only)]
    pub new_password: String,
    /// Remove the authenticator apps and the recovery codes as well (`--disable-totp`).
    #[serde(default)]
    pub disable_totp: bool,
    /// Whether the owner typed the password rather than the command drawing it; only for the
    /// audit record.
    #[serde(default)]
    pub prompted: bool,
}

/// Human label for a newly paired native capture agent.
#[derive(Deserialize, ToSchema)]
pub struct CapturePairRequest {
    pub label: String,
    /// Whether the agent may also pause and resume the whole queue from its tray and add
    /// everything from the LinkGrabber to it (`capture:queue`, RD-1100-06, RD-1240-07). Asked
    /// for explicitly or not at all: absent means `false`, so an agent paired without it can do
    /// no more than one paired before the choice existed.
    #[serde(default)]
    pub queue_control: bool,
    /// Whether the agent may install the service's offered update from its tray
    /// (`capture:server_update`, RD-1240-25). Off when absent, like `queue_control`: without it
    /// the tray's entry opens the update page in the browser.
    #[serde(default)]
    pub server_update: bool,
    /// Days until the token expires, 1 to 3650 (RD-1110-07). Absent never expires, which is
    /// what every token paired before the choice existed does.
    #[serde(default)]
    pub expires_in_days: Option<u32>,
}

/// Pairing request for a machine API token.
///
/// Separate from [`CapturePairRequest`] because a capture agent has no choice of API areas: it
/// always gets `capture:*`, and `capture:queue` and `capture:server_update` on request, while an API client picks its areas.
#[derive(Deserialize, ToSchema)]
pub struct ApiTokenRequest {
    pub label: String,
    /// The areas this token may reach, as scope strings.
    ///
    /// Empty mints `api:read`. A caller that names scopes gets exactly those: nothing here
    /// widens a request, because a minting call that quietly grants more than it was asked
    /// for is the one mistake this whole model exists to prevent.
    #[serde(default)]
    pub scopes: Vec<String>,
    /// Days until the token expires, 1 to 3650 (RD-1110-07). Absent never expires; an expired
    /// token is refused like a revoked one.
    #[serde(default)]
    pub expires_in_days: Option<u32>,
    /// Calls the token may make per minute, 1 to 6000, REST and MCP together (RD-1200-04).
    /// Absent is no limit; a call above it is refused with `429 api.token_rate_limited`.
    #[serde(default)]
    pub calls_per_minute: Option<u32>,
}

/// The new set of areas for a token that already exists.
///
/// Only the areas: no label, and above all no bearer. Re-scoping is not a re-issue, and a DTO
/// that could carry a new secret would invite one.
#[derive(Deserialize, ToSchema)]
pub struct ApiTokenScopesRequest {
    /// The areas the token holds from now on, as scope strings — the complete set, not a delta.
    ///
    /// A replacement rather than an add/remove pair because the caller sends what it sees in
    /// the form, and two clients editing the same token should not silently merge their
    /// intentions. Empty is refused: it has no legacy meaning here, and "no access at all" is
    /// spelled by revoking the token.
    pub scopes: Vec<String>,
}

/// The limits of a token that already exists (RD-1200-04).
///
/// The complete set, like [`ApiTokenScopesRequest`]: what the form shows is what the token
/// keeps, so an absent or `null` limit is no limit, not "unchanged".
#[derive(Deserialize, ToSchema)]
pub struct ApiTokenLimitsRequest {
    /// Calls per minute, 1 to 6000, REST and MCP together; absent or `null` is no limit.
    #[serde(default)]
    pub calls_per_minute: Option<u32>,
}

/// One area a token can be granted, with what it costs and what it reaches.
///
/// Sent to the token editor so the choice is made against real numbers. Everything here is
/// derived from the same table that enforces the scopes, so the preview cannot drift away
/// from the behaviour it is previewing.
#[derive(Debug, Serialize, ToSchema)]
pub struct ScopeDescriptor {
    /// The scope string, e.g. `api:queue`.
    pub scope: String,
    /// What holding this scope also confers, e.g. `api:read` for anything that acts.
    pub implies: Vec<String>,
    /// How many API operations a token holding exactly this scope reaches, implications
    /// included.
    pub operations: u32,
    /// Whether this area carries stored credentials or service administration.
    ///
    /// Flagged rather than left to the label: these are the two areas nothing else confers,
    /// and the two whose consequences are worst to grant by accident.
    pub sensitive: bool,
}

/// One-time bearer plus its revocable metadata.
#[derive(Serialize, ToSchema)]
pub struct CapturePairResponse {
    pub bearer: String,
    pub token: rd_core::CaptureToken,
}
