[package]
name = "rd-plugin-dropbox-crawler"
version = "1.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dropbox-common = { path = "../dropbox-common" }
plugin-common = { path = "../common" }
plugin-guest-crawler = { path = "../guest-crawler" }
serde_json.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[lints]
workspace = true
