//! Migration-forward: a database that stopped at an older release must upgrade cleanly.
//!
//! Part of the RD-140-04 recovery matrix, and the cheapest part by a wide margin. Every
//! other test in this repository starts from an empty database, which means the migration
//! chain is only ever exercised on a schema that has no rows in it — the one case where a
//! migration cannot lose anything. What a user actually does is upgrade an installation with
//! a queue in it, and the failure mode is silent: a migration that drops or mangles a column
//! passes an empty-database test and destroys real data.
//!
//! ## Why a schema prefix rather than an old binary
//!
//! The obvious fixture is a database file produced by the released build. It was rejected:
//! it would have to be regenerated by checking out and building each tag, the files would be
//! binary blobs nobody can review in a diff, and a fixture for a release nobody kept a build
//! of could never be produced at all.
//!
//! Applying the first *N* migrations instead reconstructs exactly the schema that release
//! shipped, from the repository alone, reproducibly, and reviewably — the migrations are the
//! definition of what a release's schema was. The seed rows then go in through raw SQL,
//! because the facade only speaks today's schema.
//!
//! ## What is deliberately not asserted
//!
//! That the whole of an old database survives. The seed is the queue core — a package, its
//! download, and a chunk checkpoint — because those are the rows whose loss is unrecoverable:
//! settings can be re-entered and a category redrawn, but bytes already on disk that the
//! database no longer accounts for are re-downloaded at best and orphaned at worst.

use std::borrow::Cow;

use sqlx::{Connection, SqliteConnection, migrate::Migrator};

/// Release baselines: the number of migrations each shipped with.
///
/// Read off the tags with
/// `git ls-tree -r --name-only <tag> crates/rd-db/migrations | wc -l`. Add a row per release
/// rather than only keeping the newest: the point is the *upgrade path*, and an installation
/// that skipped three releases takes a path no single-step test covers.
const BASELINES: &[(&str, i64)] = &[("0.6.0", 33), ("0.9.2", 47)];

/// Migration numbers that were claimed and never shipped, and never will be.
///
/// Two branches each took the next free number, only one of them landed, and renumbering the
/// survivor would change a migration that installations have already applied. The numbers are
/// therefore burnt: nothing may reuse them, and the count below is what stops this file from
/// reading a gap as a missing migration. The one place they are named.
const RESERVED_GAPS: &[i64] = &[66, 68, 88];

/// Migration numbers a parallel branch holds and that arrive when it lands.
///
/// Different from [`RESERVED_GAPS`] and deliberately a second list: a reserved number is burnt
/// for good, while one of these is a migration that exists — on another branch — and arrives
/// the moment that branch lands. **This list must be empty on `development`**: if a number is
/// still here after the branches merged, the migration it names really did go missing. It does
/// not enter [`shipped_by`], because every entry is above every release baseline and so changes
/// no release's count.
///
/// Emptied at the RD-110-19 merge, 2026-09-22 (`0082` landed with RD-110-08), refilled with
/// `0085` while RD-103-02 held `0086` on its own branch, and emptied again at that merge on
/// 2026-09-22. Twice now this list has done its job: it kept a hole that belonged to a parallel
/// branch from being burnt into RESERVED_GAPS, and the merge closed it.
///
/// Refilled a third time on 2026-09-22 with `0088`, which `feat/1.2.0-regelformat` (RD-120-12)
/// held while `feat/1.2.0-mega` (RD-120-11) took `0089`. **That branch landed the same day
/// without needing its number** — the job turned out to be a decision with no code — so the
/// alternative the entry itself named was taken: `0088` is burnt and now sits in
/// [`RESERVED_GAPS`]. A third time, then, this list did the one thing it exists for: it kept a
/// hole belonging to a parallel branch from being burnt too early, and the merge resolved it
/// deliberately instead of leaving a gap nobody could explain later.
///
/// Refilled a fourth time on 2026-09-23 with `0091`, which RD-120-30 holds on its own branch
/// while `feat/1.2.0-karten-seitenverhaeltnis` (RD-120-42) takes `0092`, and emptied again the
/// same day when RD-120-30 landed `0091_auth_flow_key_ref.sql` and RD-120-42 rebased onto it.
///
/// Refilled a fifth time on 2026-09-25 with `0094`, which a parallel branch of the 1.3 wave
/// holds while RD-130-07 takes `0095`, and emptied at the 1.3 integration merge that landed
/// `0094_candidate_cached_by.sql` (RD-130-11).
const PENDING_GAPS: &[i64] = &[];

/// How many migrations a release that stopped at `version` actually shipped.
fn shipped_by(version: i64) -> i64 {
    version - RESERVED_GAPS.iter().filter(|gap| **gap <= version).count() as i64
}

/// A migrator holding only the migrations a given release had applied.
fn migrator_up_to(version: i64) -> Migrator {
    let full = sqlx::migrate!();
    let prefix: Vec<_> = full
        .migrations
        .iter()
        .filter(|migration| migration.version <= version)
        .cloned()
        .collect();
    assert_eq!(
        prefix.len() as i64,
        shipped_by(version),
        "migrations are expected to be numbered 1..N, with only the reserved gaps {RESERVED_GAPS:?} missing"
    );
    Migrator {
        migrations: Cow::Owned(prefix),
        ..sqlx::migrate!()
    }
}

/// Seeds the queue core through raw SQL, using only columns present since `0001_initial`.
async fn seed(connection: &mut SqliteConnection) -> anyhow::Result<()> {
    sqlx::query(
        "INSERT INTO packages (id, name, state, destination, priority, created_at, updated_at)
         VALUES ('019d0000-0000-7000-8000-0000000000a1', 'Old package', 'queued', 'downloads',
                 0, '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z')",
    )
    .execute(&mut *connection)
    .await?;
    sqlx::query(
        "INSERT INTO downloads (id, package_id, source_url, file_name, state, total_bytes,
                                committed_bytes, created_at, updated_at)
         VALUES ('019d0000-0000-7000-8000-0000000000d1', '019d0000-0000-7000-8000-0000000000a1',
                 'https://files.example.test/old.bin', 'old.bin', 'queued', 4096, 1024,
                 '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z')",
    )
    .execute(&mut *connection)
    .await?;
    sqlx::query(
        "INSERT INTO chunks (id, download_id, start_offset, end_offset, committed_offset,
                             updated_at)
         VALUES ('019d0000-0000-7000-8000-0000000000c1',
                 '019d0000-0000-7000-8000-0000000000d1', 0, 4096, 1024,
                 '2026-01-01T00:00:00Z')",
    )
    .execute(&mut *connection)
    .await?;
    Ok(())
}

/// Builds a database at `version`, seeds it, and returns its path.
async fn seeded_at(
    directory: &std::path::Path,
    version: i64,
) -> anyhow::Result<std::path::PathBuf> {
    let path = directory.join("rdownloader.sqlite3");
    let url = format!("sqlite://{}?mode=rwc", path.display());
    let mut connection = SqliteConnection::connect(&url).await?;
    sqlx::query("PRAGMA foreign_keys = ON")
        .execute(&mut connection)
        .await?;
    migrator_up_to(version).run(&mut connection).await?;
    seed(&mut connection).await?;
    connection.close().await?;
    Ok(path)
}

/// The queue core of an older installation survives the upgrade, byte counts included.
#[tokio::test]
async fn every_release_baseline_upgrades_with_its_queue_intact() {
    for (release, version) in BASELINES {
        let directory = tempfile::tempdir().expect("tempdir");
        let path = seeded_at(directory.path(), *version)
            .await
            .unwrap_or_else(|error| panic!("{release}: seed at migration {version}: {error}"));

        // Opening is what applies the remaining migrations, exactly as a restart would.
        let database = rd_db::Database::open(&path)
            .await
            .unwrap_or_else(|error| panic!("{release}: upgrade from migration {version}: {error}"));

        let packages = database.list_packages().await.expect("packages");
        assert_eq!(packages.len(), 1, "{release}: the package did not survive");
        assert_eq!(packages[0].name, "Old package", "{release}");

        let downloads = database.list_downloads().await.expect("downloads");
        assert_eq!(
            downloads.len(),
            1,
            "{release}: the download did not survive"
        );
        let download = &downloads[0];
        assert_eq!(download.file_name, "old.bin", "{release}");
        assert_eq!(
            download.source.as_str(),
            "https://files.example.test/old.bin",
            "{release}"
        );
        // The number that matters: bytes already on disk must still be accounted for, or the
        // upgrade silently re-downloads them.
        assert_eq!(
            download.committed_bytes.get(),
            1024,
            "{release}: committed bytes were not carried forward"
        );
        assert_eq!(
            download.total_bytes.map(rd_core::ByteCount::get),
            Some(4096),
            "{release}"
        );
    }
}

/// An upgraded database is writable, not merely readable.
///
/// A migration can leave a schema that reads back correctly and rejects the next insert — a
/// tightened constraint, a column that became `NOT NULL` without a default. Reading alone
/// would not notice until the first real download.
#[tokio::test]
async fn an_upgraded_database_still_accepts_writes() {
    let directory = tempfile::tempdir().expect("tempdir");
    let path = seeded_at(directory.path(), BASELINES[0].1)
        .await
        .expect("seed");
    let database = rd_db::Database::open(&path).await.expect("upgrade");

    let package = database
        .create_package(rd_db::NewPackage {
            id: rd_core::PackageId::new(),
            name: "After the upgrade".to_owned(),
            destination: "downloads".to_owned(),
            category_id: None,
            priority: rd_core::DownloadPriority::default(),
            postprocess_level: None,
            script: None,
            enrichment: Vec::new(),
        })
        .await
        .expect("create a package on the upgraded schema");
    assert_eq!(database.list_packages().await.expect("packages").len(), 2);
    assert_eq!(package.name, "After the upgrade");
}

/// Startup recovery runs against an upgraded database without losing the checkpoint.
///
/// `recover_interrupted` resets active states to queued, and it is the first thing that
/// touches an upgraded database on a real start. A checkpoint it discarded would be bytes
/// re-downloaded on every upgrade.
#[tokio::test]
async fn recovery_after_an_upgrade_keeps_the_checkpoint() {
    let directory = tempfile::tempdir().expect("tempdir");
    let path = seeded_at(directory.path(), BASELINES[1].1)
        .await
        .expect("seed");
    let database = rd_db::Database::open(&path).await.expect("upgrade");

    database.recover_interrupted().await.expect("recover");
    let downloads = database.list_downloads().await.expect("downloads");
    assert_eq!(
        downloads[0].committed_bytes.get(),
        1024,
        "recovery discarded a checkpoint that the file on disk still matches"
    );
}

/// The reserved numbers really are absent, and nothing else is.
///
/// Without this the tolerance above would hide a genuinely missing migration: a chain that
/// skipped 0080 by accident would simply be declared to have another reserved gap.
#[test]
fn only_the_reserved_numbers_are_missing_from_the_chain() {
    let migrations = sqlx::migrate!();
    let present: Vec<i64> = migrations
        .migrations
        .iter()
        .map(|migration| migration.version)
        .collect();
    let highest = *present.last().expect("at least one migration");
    let missing: Vec<i64> = (1..=highest)
        .filter(|version| !present.contains(version))
        .collect();
    let mut expected: Vec<i64> = RESERVED_GAPS.iter().chain(PENDING_GAPS).copied().collect();
    expected.sort_unstable();
    assert_eq!(
        missing, expected,
        "a migration number is missing that is neither reserved nor held by a parallel branch"
    );
    let baseline = BASELINES.last().map_or(0, |(_, count)| *count);
    assert!(
        PENDING_GAPS.iter().all(|gap| *gap > baseline),
        "a pending gap below a release baseline would silently change that release's count"
    );
}

/// A subscription stored before RD-120-37 keeps the list view, and no autoplay, on upgrade.
///
/// The whole promise of migration `0090` is that nobody who changes nothing sees anything new;
/// this is that promise measured on a row written by the schema one migration earlier.
#[tokio::test]
async fn a_subscription_from_before_the_view_choice_keeps_the_list() {
    let directory = tempfile::tempdir().expect("tempdir");
    let path = seeded_at(directory.path(), 89).await.expect("seed at 0089");
    {
        let url = format!("sqlite://{}", path.display());
        let mut connection = SqliteConnection::connect(&url).await.expect("connect");
        sqlx::query(
            "INSERT INTO subscriptions (id, name, url, kind, enabled, mode, priority,
                                        interval_seconds, created_at, updated_at)
             VALUES ('019d0000-0000-7000-8000-0000000000e1', 'Old search',
                     'https://indexer.example.test/api', 'indexer', 1, 'review', 0, 3600,
                     '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z')",
        )
        .execute(&mut connection)
        .await
        .expect("insert a subscription on the 0089 schema");
        connection.close().await.expect("close");
    }

    let database = rd_db::Database::open(&path).await.expect("upgrade");
    let subscriptions = database.list_subscriptions().await.expect("subscriptions");
    assert_eq!(subscriptions.len(), 1);
    assert_eq!(subscriptions[0].view, rd_core::SubscriptionView::List);
    assert!(!subscriptions[0].autoplay);
}

/// A subscription stored before RD-120-42 gets the `2:1` card ratio on upgrade.
///
/// `2:1` is the ratio closest to the fixed height every card had before the choice existed, so
/// migration `0092` changes nothing anybody sees; this measures that on a row written by the
/// schema from before it, with a view and autoplay already chosen that must survive untouched.
#[tokio::test]
async fn a_subscription_from_before_the_card_ratio_gets_two_to_one() {
    let directory = tempfile::tempdir().expect("tempdir");
    let path = seeded_at(directory.path(), 90).await.expect("seed at 0090");
    {
        let url = format!("sqlite://{}", path.display());
        let mut connection = SqliteConnection::connect(&url).await.expect("connect");
        sqlx::query(
            "INSERT INTO subscriptions (id, name, url, kind, enabled, mode, priority,
                                        interval_seconds, view, autoplay, created_at, updated_at)
             VALUES ('019d0000-0000-7000-8000-0000000000e2', 'Old music',
                     'https://indexer.example.test/api', 'indexer', 1, 'review', 0, 3600,
                     'cards', 1, '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z')",
        )
        .execute(&mut connection)
        .await
        .expect("insert a subscription on the 0090 schema");
        connection.close().await.expect("close");
    }

    let database = rd_db::Database::open(&path).await.expect("upgrade");
    let subscriptions = database.list_subscriptions().await.expect("subscriptions");
    assert_eq!(subscriptions.len(), 1);
    assert_eq!(
        subscriptions[0].card_ratio,
        rd_core::SubscriptionCardRatio::TwoOne
    );
    assert_eq!(subscriptions[0].view, rd_core::SubscriptionView::Cards);
    assert!(subscriptions[0].autoplay);
}

/// RD-130-07: migration `0095` merges `comics` and `magazines` into `ebooks`, leaves `graphics`
/// alone, and lets go of the compiled-in pack's switches.
///
/// Seeded on the `0093` schema, the last one on this branch below `0095`; `0094` belongs to a
/// parallel branch and touches neither table.
#[tokio::test]
async fn the_site_rule_groups_are_merged_into_ebooks_and_off_wins() {
    let directory = tempfile::tempdir().expect("tempdir");
    let path = seeded_at(directory.path(), 93).await.expect("seed at 0093");
    {
        let url = format!("sqlite://{}", path.display());
        let mut connection = SqliteConnection::connect(&url).await.expect("connect");
        for (id, group) in [
            ("old-magazine", "magazines"),
            ("old-comic", "comics"),
            ("old-graphics", "graphics"),
            ("old-board", "board"),
        ] {
            sqlx::query(
                "INSERT INTO site_rules (id, name, rule_group, enabled, rule_json, created_at,
                                         updated_at)
                 VALUES (?1, ?1, ?2, 1, json_object('id', ?1, 'group', ?2),
                         '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z')",
            )
            .bind(id)
            .bind(group)
            .execute(&mut connection)
            .await
            .expect("insert a site rule on the 0093 schema");
        }
        for (scope, key, enabled) in [
            ("rule", "scnlog", 0),
            ("group", "magazines", 0),
            ("group", "ebooks", 1),
            ("group", "board", 0),
            ("group", "graphics", 0),
        ] {
            sqlx::query(
                "INSERT INTO site_rule_switches (scope, key, enabled, updated_at)
                 VALUES (?1, ?2, ?3, '2026-01-01T00:00:00Z')",
            )
            .bind(scope)
            .bind(key)
            .bind(enabled)
            .execute(&mut connection)
            .await
            .expect("insert a switch on the 0093 schema");
        }
        connection.close().await.expect("close");
    }

    let database = rd_db::Database::open(&path).await.expect("upgrade");
    let rules = database.list_site_rules().await.expect("site rules");
    for rule in &rules {
        let expected = match rule.id.as_str() {
            "old-board" => "board",
            "old-graphics" => "graphics",
            _ => "ebooks",
        };
        assert_eq!(rule.group, expected, "{}: the column", rule.id);
        assert_eq!(rule.rule["group"], expected, "{}: the body", rule.id);
    }
    assert_eq!(rules.len(), 4);

    let mut switches: Vec<(String, String, bool)> = database
        .list_site_rule_switches()
        .await
        .expect("switches")
        .into_iter()
        .map(|row| (row.scope, row.key, row.enabled))
        .collect();
    switches.sort();
    assert_eq!(
        switches,
        [
            ("group".to_owned(), "board".to_owned(), false),
            // `ebooks` was on and `magazines` off: the merged group is off.
            ("group".to_owned(), "ebooks".to_owned(), false),
            // `graphics` is a group of its own and keeps its switch.
            ("group".to_owned(), "graphics".to_owned(), false),
        ],
        "the merged groups' rows and the compiled-in pack's rule rows are gone"
    );
}
