//! Migration-forward: a database that stopped at an older release must upgrade cleanly.
//!
//! Part of the RD-140-04 recovery matrix, and the cheapest part by a wide margin. Every
//! other test in this repository starts from an empty database, which means the migration
//! chain is only ever exercised on a schema that has no rows in it — the one case where a
//! migration cannot lose anything. What a user actually does is upgrade an installation with
//! a queue in it, and the failure mode is silent: a migration that drops or mangles a column
//! passes an empty-database test and destroys real data.
//!
//! ## Why a schema prefix rather than an old binary
//!
//! The obvious fixture is a database file produced by the released build. It was rejected:
//! it would have to be regenerated by checking out and building each tag, the files would be
//! binary blobs nobody can review in a diff, and a fixture for a release nobody kept a build
//! of could never be produced at all.
//!
//! Applying the first *N* migrations instead reconstructs exactly the schema that release
//! shipped, from the repository alone, reproducibly, and reviewably — the migrations are the
//! definition of what a release's schema was. The seed rows then go in through raw SQL,
//! because the facade only speaks today's schema.
//!
//! ## What the fixture holds, and what it leaves out
//!
//! The queue first — packages and downloads in several states and a chunk checkpoint — because
//! those are the rows whose loss is unrecoverable: settings can be re-entered and a category
//! redrawn, but bytes already on disk that the database no longer accounts for are re-downloaded
//! at best and orphaned at worst. Next to it, every row a migration after `0033` *rewrites*
//! rather than merely widens, and an account with its secret reference: see [`fixture`].
//!
//! Left out is the whole of an old database. A migration that only adds a nullable column
//! cannot lose a row, and a fixture that tried to fill every table would stop being reviewable.
//!
//! The suite is one binary with a module per concern, like the `rd-api` suites (RD-150-10):
//! [`baselines`] upgrades every release, [`per_migration`] measures single migrations on the
//! schema right before them.

mod baselines;
mod fixture;
mod per_migration;

use std::borrow::Cow;

use sqlx::{Connection, SqliteConnection, migrate::Migrator};

/// Release baselines: the highest migration number each release shipped with.
///
/// Read off the tags with
/// `git ls-tree -r --name-only <tag> crates/rd-db/migrations | tail -1`. The number is not the
/// count once the chain has gaps — 1.1.0 stopped at `0087` with 85 migrations — and
/// [`shipped_by`] checks the count against it. Add a row per release rather than only keeping
/// the newest: the point is the *upgrade path*, and an installation that skipped three releases
/// takes a path no single-step test covers. 1.5.0 is the head of the chain today and upgrades by
/// nothing; it is here for the first release that adds a migration after it.
const BASELINES: &[(&str, i64)] = &[
    ("0.6.0", 33),
    ("0.9.2", 47),
    ("1.0.0", 55),
    ("1.1.0", 87),
    ("1.2.0", 93),
    ("1.3.0", 96),
    ("1.4.0", 98),
    ("1.5.0", 108),
];

/// Migration numbers that were claimed and never shipped, and never will be.
///
/// Two branches each took the next free number, only one of them landed, and renumbering the
/// survivor would change a migration that installations have already applied. The numbers are
/// therefore burnt: nothing may reuse them, and the count below is what stops this file from
/// reading a gap as a missing migration. The one place they are named.
const RESERVED_GAPS: &[i64] = &[66, 68, 88];

/// Migration numbers a parallel branch holds and that arrive when it lands.
///
/// Different from [`RESERVED_GAPS`] and deliberately a second list: a reserved number is burnt
/// for good, while one of these is a migration that exists — on another branch — and arrives
/// the moment that branch lands. **This list must be empty on `development`**: if a number is
/// still here after the branches merged, the migration it names really did go missing. It does
/// not enter [`shipped_by`], because every entry is above every release baseline and so changes
/// no release's count.
///
/// Emptied at the RD-110-19 merge, 2026-09-22 (`0082` landed with RD-110-08), refilled with
/// `0085` while RD-103-02 held `0086` on its own branch, and emptied again at that merge on
/// 2026-09-22. Twice now this list has done its job: it kept a hole that belonged to a parallel
/// branch from being burnt into RESERVED_GAPS, and the merge closed it.
///
/// Refilled a third time on 2026-09-22 with `0088`, which `feat/1.2.0-regelformat` (RD-120-12)
/// held while `feat/1.2.0-mega` (RD-120-11) took `0089`. **That branch landed the same day
/// without needing its number** — the job turned out to be a decision with no code — so the
/// alternative the entry itself named was taken: `0088` is burnt and now sits in
/// [`RESERVED_GAPS`]. A third time, then, this list did the one thing it exists for: it kept a
/// hole belonging to a parallel branch from being burnt too early, and the merge resolved it
/// deliberately instead of leaving a gap nobody could explain later.
///
/// Refilled a fourth time on 2026-09-23 with `0091`, which RD-120-30 holds on its own branch
/// while `feat/1.2.0-karten-seitenverhaeltnis` (RD-120-42) takes `0092`, and emptied again the
/// same day when RD-120-30 landed `0091_auth_flow_key_ref.sql` and RD-120-42 rebased onto it.
///
/// Refilled a fifth time on 2026-09-25 with `0094`, which a parallel branch of the 1.3 wave
/// holds while RD-130-07 takes `0095`, and emptied at the 1.3 integration merge that landed
/// `0094_candidate_cached_by.sql` (RD-130-11).
///
/// Refilled a sixth time on 2026-09-27 with `0099` and `0100`, which `feat/1.5-dedupe`
/// (RD-150-01) holds while the 1.5 wave-1 integration lands `0101` to `0104`. Emptied when that
/// branch merges; emptied at the 1.5 wave-2 integration merge.
const PENDING_GAPS: &[i64] = &[];

/// How many migrations a release that stopped at `version` actually shipped.
fn shipped_by(version: i64) -> i64 {
    version - RESERVED_GAPS.iter().filter(|gap| **gap <= version).count() as i64
}

/// A migrator holding only the migrations a given release had applied.
fn migrator_up_to(version: i64) -> Migrator {
    let full = sqlx::migrate!();
    let prefix: Vec<_> = full
        .migrations
        .iter()
        .filter(|migration| migration.version <= version)
        .cloned()
        .collect();
    assert_eq!(
        prefix.len() as i64,
        shipped_by(version),
        "migrations are expected to be numbered 1..N, with only the reserved gaps {RESERVED_GAPS:?} missing"
    );
    Migrator {
        migrations: Cow::Owned(prefix),
        ..sqlx::migrate!()
    }
}

/// Opens a raw connection to a database file, foreign keys on as the service has them.
async fn connect(path: &std::path::Path) -> anyhow::Result<SqliteConnection> {
    let url = format!("sqlite://{}?mode=rwc", path.display());
    let mut connection = SqliteConnection::connect(&url).await?;
    sqlx::query("PRAGMA foreign_keys = ON")
        .execute(&mut connection)
        .await?;
    Ok(connection)
}

/// Builds an empty database with the schema of migration `version` and returns its path.
async fn schema_at(
    directory: &std::path::Path,
    version: i64,
) -> anyhow::Result<std::path::PathBuf> {
    let path = directory.join("rdownloader.sqlite3");
    let mut connection = connect(&path).await?;
    migrator_up_to(version).run(&mut connection).await?;
    connection.close().await?;
    Ok(path)
}

/// Builds a database at `version`, seeds the release fixture, and returns its path.
async fn seeded_at(
    directory: &std::path::Path,
    version: i64,
) -> anyhow::Result<std::path::PathBuf> {
    let path = schema_at(directory, version).await?;
    let mut connection = connect(&path).await?;
    fixture::seed(&mut connection, version).await?;
    connection.close().await?;
    Ok(path)
}
