[package]
name = "rd-plugin-torbox-jobs"
version = "1.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
md-5.workspace = true
plugin-common = { path = "../common" }
plugin-guest-remote-job = { path = "../guest-remote-job" }
serde.workspace = true
serde_json.workspace = true
torrent-common = { path = "../torrent-common" }

[lib]
crate-type = ["rlib", "cdylib"]

[package.metadata.component]
package = "rdownloader:torbox-jobs"

[package.metadata.component.target]
path = "../../crates/rd-plugin-api/wit"
world = "remote-job-plugin"

[lints]
workspace = true

# The package is `md-5`, the library `md5`; cargo-machete looks for the former.
[package.metadata.cargo-machete]
ignored = ["md-5"]
