[package]
name = "rd-plugin-pcloud"
version = "1.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pcloud-common = { path = "../pcloud-common" }
plugin-common = { path = "../common" }
plugin-guest = { path = "../guest" }
url.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-trait.workspace = true
rd-plugin-api = { path = "../../crates/rd-plugin-api" }
rd-plugin-types = { path = "../../crates/rd-plugin-types" }

[lib]
crate-type = ["rlib"]

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
