#!/usr/bin/env bash
#
# Builds the Windows installer from the unpacked release zip (RD-180-05), with WiX 5 and
# packaging/msi/rdownloader.wxs. The MSI holds exactly the zip's files, plus the install-kind
# marker `msi` that moves the service's data into %LOCALAPPDATA%\rDownloader. It needs Windows:
# release.yml and installers.yml run it on windows-2025 under Git Bash, after
#   dotnet tool install --global wix --version 5.0.2
#   wix extension add --global WixToolset.UI.wixext/5.0.2 WixToolset.Util.wixext/5.0.2
# WiX 5 rather than 6 or later: from 6 on, WiX asks for its maintenance-fee EULA to be accepted.
#
# Usage:
#   scripts/package-msi.sh <unpacked-zip-dir> <out.msi>
#   scripts/package-msi.sh --sources-only <unpacked-zip-dir> <out-dir>   # generated sources, no wix
#
# The MSI's version is the three numbers of the one VERSION.txt names: MSI compares no more, and
# a pre-release suffix is not allowed in it (1.8.0-beta.1 is 1.8.0).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
sources_only=0
if [[ "${1:-}" == --sources-only ]]; then
    sources_only=1
    shift
fi
stage="${1:?usage: scripts/package-msi.sh [--sources-only] <unpacked-zip-dir> <out.msi|out-dir>}"
out="${2:?usage: scripts/package-msi.sh [--sources-only] <unpacked-zip-dir> <out.msi|out-dir>}"

# A native Windows program takes Windows paths; under Git Bash cygpath makes them.
winpath() {
    if command -v cygpath > /dev/null; then cygpath -w "$1"; else printf '%s' "$1"; fi
}

# shellcheck source=lib/archive-layout.sh
source "$ROOT/scripts/lib/archive-layout.sh"
while IFS= read -r entry; do
    if [[ ! -f "$stage/$entry" ]]; then
        echo "$stage has no $entry; unpack rdownloader-windows-x86_64.zip there" >&2
        exit 1
    fi
done < <(rd_archive_entries windows)
if [[ -f "$stage/UNVERIFIED.txt" ]]; then
    echo "$stage is an unverified package (UNVERIFIED.txt); no installer is built from it" >&2
    exit 1
fi

version="$(sed -n '1s/^rDownloader //p' "$stage/VERSION.txt" | tr -d '\r')"
if [[ ! "$version" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(-[0-9A-Za-z.]+)?$ ]]; then
    echo "$stage/VERSION.txt names no version ('$version')" >&2
    exit 1
fi
msi_version="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.${BASH_REMATCH[3]}"
# The limits of ProductVersion: major and minor below 256, build below 65536.
if (( BASH_REMATCH[1] > 255 || BASH_REMATCH[2] > 255 || BASH_REMATCH[3] > 65535 )); then
    echo "$version does not fit an MSI ProductVersion" >&2
    exit 1
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# The bundled plugins, one component with every package: the set changes from release to
# release, and a major upgrade removes the old one before the new one is laid down.
plugins=()
for package in "$stage"/plugins/*.rdplug; do
    [[ -f "$package" ]] || continue
    name="$(basename "$package")"
    if [[ ! "$name" =~ ^[a-z0-9][a-z0-9._-]*\.rdplug$ ]]; then
        echo "unexpected plugin file name: $name" >&2
        exit 1
    fi
    plugins+=("$name")
done
if [[ "${#plugins[@]}" -eq 0 ]]; then
    echo "$stage/plugins holds no .rdplug; the installer would start without a hoster" >&2
    exit 1
fi
{
    echo '<?xml version="1.0" encoding="utf-8"?>'
    echo '<!-- Generated by scripts/package-msi.sh: the bundled plugins of this release. -->'
    echo '<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">'
    echo '  <Fragment>'
    echo '    <ComponentGroup Id="Plugins" Directory="PluginsFolder">'
    echo '      <Component Id="Plugins" Guid="2C93C486-60A5-42CB-8546-66CB5487968E">'
    echo '        <RegistryValue Root="HKCU" Key="Software\rDownloader\Installer" Name="Plugins" Type="integer" Value="1" KeyPath="yes" />'
    index=0
    for name in "${plugins[@]}"; do
        index=$((index + 1))
        echo "        <File Id=\"plugin$index\" Name=\"$name\" Source=\"\$(var.Stage)\\plugins\\$name\" />"
    done
    echo '        <RemoveFolder Id="RemovePluginsFolder" On="uninstall" />'
    echo '      </Component>'
    echo '    </ComponentGroup>'
    echo '  </Fragment>'
    echo '</Wix>'
} > "$work/plugins.wxs"

# The licence page WixUI_Minimal shows, from LICENSE: RTF with its three special characters
# escaped and every line a paragraph.
{
    printf '%s\n' '{\rtf1\ansi\deff0{\fonttbl{\f0\fmodern Consolas;}}\f0\fs16'
    sed -e 's/\r$//' -e 's/\\/\\\\/g' -e 's/{/\\{/g' -e 's/}/\\}/g' -e 's/$/\\par/' "$stage/LICENSE"
    printf '%s\n' '}'
} > "$work/license.rtf"

printf 'msi\n' > "$work/install-kind"

arguments=(build -arch x64
    -ext WixToolset.UI.wixext -ext WixToolset.Util.wixext
    -d "Version=$msi_version"
    -d "Stage=$(winpath "$stage")"
    -d "InstallKind=$(winpath "$work/install-kind")"
    -d "LicenseRtf=$(winpath "$work/license.rtf")"
    -d "Icon=$(winpath "$ROOT/resources/rdownloader.ico")"
    "$(winpath "$ROOT/packaging/msi/rdownloader.wxs")" "$(winpath "$work/plugins.wxs")")

if [[ "$sources_only" -eq 1 ]]; then
    mkdir -p "$out"
    cp "$work/plugins.wxs" "$work/license.rtf" "$work/install-kind" "$out/"
    printf '%s\n' "${arguments[@]}" > "$out/wix-arguments.txt"
    echo "    sources in $out (rdownloader $version, MSI $msi_version, ${#plugins[@]} plugins)"
    exit 0
fi

if ! command -v wix > /dev/null; then
    echo "wix is not installed (dotnet tool install --global wix --version 5.0.2)" >&2
    exit 1
fi
mkdir -p "$(dirname "$out")"
rm -f "$out"
wix "${arguments[@]}" -o "$(winpath "$out")"
echo "    $out (rdownloader $version, MSI $msi_version, ${#plugins[@]} plugins)"
