[package]
name = "rd-plugin-pcloud-oauth"
version = "1.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pcloud-common = { path = "../pcloud-common" }
plugin-common = { path = "../common" }
plugin-guest-oauth = { path = "../guest-oauth" }

[lib]
crate-type = ["rlib", "cdylib"]

[lints]
workspace = true
