[package]
name = "rd-plugin-pixeldrain-crawler"
version = "1.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
plugin-guest-crawler = { path = "../guest-crawler" }
serde.workspace = true
serde_json.workspace = true
url.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[lints]
workspace = true
