import type { Settings } from '@/api/types'
import { GIB, MIB } from '@/utils/format'

/**
 * The settings document as the view holds it before the service has answered: every field the
 * tabs bind to, so no tab reads an undefined value while the first request is in flight.
 * Only the shape matters here; the values the service reports replace all of it.
 */
export function defaultSettings(): Settings {
  return {
    max_active_files: 3,
    max_chunks_per_file: 4,
    max_connections_per_host: 6,
    nntp_connections_per_file: 0,
    speed_limit_bytes_per_second: null,
    generate_sha256: true,
    global_proxy_profile_id: null,
    custom_ca_pem: null,
    auto_extract: false,
    archive_max_files: 20_000,
    archive_max_uncompressed_bytes: String(100 * GIB),
    rar_executable: null,
    rar_tool: 'unrar',
    max_retries: 8,
    keep_import_history: true,
    auto_remove_finished: false,
    auto_remove_delay_hours: 24,
    auto_remove_keep_failed: true,
    delete_archives_after_extract: false,
    passwords_file: null,
    admin_login_disabled: false,
    default_level: 'unpack',
    pause_during_postprocess: true,
    cleanup_extensions: ['nfo', 'sfv', 'srr', 'url', 'nzb'],
    ignore_samples: true,
    recursive_unpack: false,
    sfv_verify: true,
    safe_postproc: true,
    delete_par2: false,
    enable_all_par: false,
    plugin_steps: [],
    metadata_enrichment_enabled: false,
    sample_max_bytes: String(300 * MIB),
    scripts_directory: null,
    script_timeout_seconds: 3600,
    upload_enabled: false,
    upload_remote: null,
    upload_mode: 'copy',
    rclone_executable: null,
    excluded_domains_file: null,
    dlc_service_enabled: false,
    subscription_item_images_enabled: true,
    dlc_service_endpoint: null,
    vendor_directory: null,
    managed_tools_enabled: false,
    managed_tools_manifest_url: null,
    tool_compatibility_overrides: [],
    ui_port: null,
    media_ytdlp_executable: null,
    media_ffmpeg_executable: null,
    media_default_variant: 'best',
    media_default_criteria: null,
    media_output_template: null,
    media_hosts: ['youtube.com', 'youtu.be', 'm.youtube.com', 'music.youtube.com', 'dumpert.nl'],
    media_max_parallel: 2,
    media_check_timeout_seconds: 60,
    gallery_executable: null,
    gallery_hosts: [
      'pixiv.net', 'deviantart.com', 'artstation.com', 'flickr.com',
      'danbooru.donmai.us', 'gelbooru.com', 'e621.net', 'rule34.xxx',
      'kemono.cr', 'fanbox.cc', 'redgifs.com', 'imgbox.com'
    ],
    gallery_max_parallel: 2,
    remote_max_parallel: 2,
    remote_timeout_seconds: 60,
    remote_ssh_auto_trust: false,
    record_streamlink_executable: null,
    record_default_quality: 'best',
    record_poll_interval_seconds: 120,
    record_max_parallel: 2,
    torrent_listen_port: null,
    torrent_seed_ratio: 1,
    torrent_seed_time_minutes: null,
    torrent_service_enabled: true,
    usenet_service_enabled: true,
    media_service_enabled: true,
    gallery_service_enabled: true,
    recording_service_enabled: true,
    remote_service_enabled: true,
    torrent_sharing_enabled: false,
    torrent_seeding_enabled: false,
    torrent_upload_limit_bytes_per_second: null,
  torrent_peer_addresses_visible: false,
  torrent_bind_interface: null,
  torrent_kill_switch_enabled: false,
  torrent_ip_blocklist_url: null,
  torrent_listen_mode: 'tcp_and_utp',
  torrent_peer_limit: null,
  torrent_download_limit_bytes_per_second: null,
  torrent_proxy_profile_id: null,
  torrent_upnp_enabled: false,
  torrent_announce_port: null,
  quiet_hours: { enabled: false, windows: [] },
  quiet_hours_defer_postprocess: true,
  quiet_hours_defer_notifications: true,
  completion_action: 'none',
  completion_script: null,
  completion_countdown_seconds: 60,
  power_actions_allowed: false,
  pause_on_battery: false,
  pause_on_metered: false,
  prevent_standby: false,
  prevent_display_standby: false,
  mirror_detection: true,
  reconnect_enabled: false,
  reconnect_script: null,
  reconnect_windows: [],
  reconnect_min_interval_minutes: 10,
  reconnect_timeout_seconds: 180,
  reconnect_abort_active: false,
  reconnect_ip_check_urls: [],
  bandwidth_timezone: 'Europe/Berlin',
  bandwidth_default_profile_id: null,
  storage_minimum_free_bytes: String(256 * MIB),
  storage_auto_resume: true,
  storage_unknown_size_headroom: 4,
  byte_display: 'binary',
  byte_unit: 'auto',
  title_status_enabled: true,
  disabled_plugins: [],
  stats_hourly_days: 30,
  stats_retention_days: 365,
  trusted_proxies: [],
  external_url: null,
  cookie_security: 'auto',
  session_idle_hours: 12,
  session_max_hours: 720,
  log_retention_records: 20_000,
  log_retention_days: 14,
  audit_retention_records: 100_000,
  audit_retention_days: 365,
  otlp_enabled: false,
  otlp_endpoint: '',
  otlp_timeout_seconds: 5,
  hotfolder_poll_seconds: 30
  }
}
