[package]
name = "rd-plugin-google-drive-oauth"
version = "1.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
plugin-common = { path = "../common" }
plugin-guest-oauth = { path = "../guest-oauth" }

[lib]
crate-type = ["rlib", "cdylib"]

[lints]
workspace = true
