[package]
name = "rd-plugin-box-crawler"
version = "1.2.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
box-common = { path = "../box-common" }
serde.workspace = true
serde_json.workspace = true
wit-bindgen.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[package.metadata.component]
package = "rdownloader:box-crawler"

[package.metadata.component.target]
path = "../../crates/rd-plugin-api/wit"
world = "crawler-plugin"

[lints]
workspace = true
